version: "3.7"
services:
  music-and-lyric-web:
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - "./web/build:/usr/share/nginx/html"
    ports:
      - "1234:80"
    expose:
      - 80
