version: "3.7"
services:
  music-and-lyric-web:
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - "./web/dist:/usr/share/nginx/html"
    ports:
      - "5173:80"
    expose:
      - 80
